apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
    project: practice
    author: xotam
  name: nginx1
spec:
  containers:
  - image: nginx
    name: nginx
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
    project: practice
    author: xotam
  name: nginx2
spec:
  containers:
  - image: nginx
    name: nginx
  dnsPolicy: ClusterFirst
  restartPolicy: Always
