apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-app
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - image: khotam/node-app:v1
        name: node-app
        resources:
          requests:
            cpu: 100m
            memory: 64M
          limits:
            cpu: 200m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /config
            port: 80
        env:
        - name: CPU
          valueFrom:
            resourceFieldRef:
              containerName: node-app
              resource: requests.cpu
        - name: MEMORY
          valueFrom:
            resourceFieldRef:
              containerName: node-app
              resource: requests.memory
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: info
              key: log_level
        - name: GRPC_PORT
          valueFrom:
            configMapKeyRef:
              name: info
              key: grpc_port
        - name: DB_URI
          valueFrom:
            secretKeyRef:
              name: database
              key: DB_URI
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
